### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by nirojmhj** [koirpraw/myHealth#3]

**Comment by koirpraw** [comment]
Issue with apple sign in. Getting Exception handling error as follows
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))
#0      MethodChannelSignInWithApple.getAppleIDCredential (package:sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart:86:7)
<asynchronous suspension>
#1      LoginController.appleSignIn (package:my_health/controller/LoginController.dart:62:24)
<asynchronous suspension>

**Comment by koirpraw** [comment]
Can not test facebook login: permission error!
"App not setup: This app is still in development mode and you dont have access to it. switch to a registered test user or ask an app admin for permission
<img width="464" alt="Screen Shot 2022-05-11 at 2 04 34 PM" src="https://user-images.githubusercontent.com/7278348/167936968-0cb6d68a-404d-47d1-8a92-7d387203e93c.png">
"

**Comment by koirpraw** [comment]
> Issue with apple sign in. Getting Exception handling error as follows [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)) #0 MethodChannelSignInWithApple.getAppleIDCredential (package:sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart:86:7) #1 LoginController.appleSignIn (package:my_health/controller/LoginController.dart:62:24)
> 
> <img alt="Screen Shot 2022-05-11 at 2 06 33 PM" width="1484" src="https://user-images.githubusercontent.com/7278348/167937728-4edc032c-198c-4e63-866a-a99a38b3995b.png">

**Comment by nirojmhj** [comment]
Google login resolve #51e10fd

**Comment by nirojmhj** [comment]
Google login resolve #

**Comment by nirojmhj** [comment]
Google signin resolved: 51e10fde94544a3b3201b8110cbcde156f284562
